### ISSUE TITLE
在暗背景下,如果选中时紫色的通知背景会看不见文字

### ISSUE THREAD

**Issue by v1ster** [KingJacM/eva-unit-01-theme#1]
![Whiteboard](https://user-images.githubusercontent.com/26289399/178384614-b00c4197-fd2b-4d22-be3b-1200b40ddc03.png)

**Comment by KingJacM** [comment]
fixed by setting `"list.focusBackground": "#8a55e06b"`

**Comment by v1ster** [comment]
👍
